name: AniList readme workflow
on:
    schedule:
        # Runs 3 hour
        - cron: "0 */3 * * *"
    workflow_dispatch:

jobs:
    update-readme-with-anilist:
        name: Update this repo's README with latest AniList activites
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: AniList readme workflow
              uses: K0ng2/anilist-readme@v1.4.3
              with:
                  user_id: 220152
                  max_post_count: 7
                  preferred_language: romanji
