name: Waka Readme and AniList Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AniList readme workflow
        uses: K0ng2/anilist-readme@v1.4.3
        with:
            user_id: 220152
            max_post_count: 7
            preferred_language: romaji
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: all
          TIME_RANGE: all_time
          LANG_COUNT: 8
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TITLE: true
          SHOW_MASKED_TIME: true
          CODE_LANG: markdown
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: week
          TIME_RANGE: last_7_days
          LANG_COUNT: 8
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TITLE: true
          SHOW_MASKED_TIME: true
          CODE_LANG: markdown
